### DISCUSSION TITLE
nwg-shell 0.5.23 (2023-12-02)

### DISCUSSION THREAD

**Discussion by nwg-piotr** [nwg-piotr/nwg-shell#235] [Changelog]
- css style sheets: added `*:selected` pseudo-class for hovered nwg-panel elements.

```css
/* Selected (hovered) UI elements */
*:selected {
  border: none;
  background: #cd7ebf;
  color: #fff
}
```

<hr /><em>This discussion was created from the release <a href='https://github.com/nwg-piotr/nwg-shell/releases/tag/v0.5.23'>nwg-shell 0.5.23</a>.</em>
