### DISCUSSION TITLE
nwg-panel overwrites roundings on selection.

### DISCUSSION THREAD

**Discussion by aposteeltje-bwg** [nwg-piotr/nwg-shell#534] [Q&A] [answered]
Hi all.
My nwg-panel has roundings,
but when i select a item on the panel, it highlights it with a square...
See picture below.
Can i change that behaviour?
![2025-05-17-201150_hypr_screenshot](https://github.com/user-attachments/assets/43262506-952b-4628-aac0-1fabab989f20)

**Comment by nwg-piotr** [comment, marked as answer]
Edit your css file. 

```css
#button-custom:hover {
    border: none;
    border-radius: 3px;
    background: #cd7ebf;
    color: #fff
}
```

Replace `border-radius: 3px;` with `border-radius: 30px;` or something.

**Reply by aposteeltje-bwg** [reply]
Thank you.....

**Reply by aposteeltje-bwg** [reply]
it works, but partially.....
on the left side of the panel it's ok now,
but on the right side of the panel,
i still get a square.....

https://github.com/user-attachments/assets/1aa5eb77-c3f2-4fc7-a5a5-c37cf97aa249

**Reply by aposteeltje-bwg** [reply]
This is minor,
so not really a problem.
I Love your work...
I don't want to come over as a nagger.... :-)

**Reply by nwg-piotr** [reply]
Haha! Try this at the end of your .css file:

```css
/* Selected (hovered) UI elements */
*:selected {
    border: none;
    border-radius: 30px;
    background: #cd7ebf;
    color: #fff
}
```
